# Generated by Django 6.0.5 on 2026-06-19 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cakes/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CakeFlavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavours', to='zyvaracafe.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=50)),
                ('extra_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='zyvaracafe.cake')),
            ],
        ),
    ]
